name: Update Glue Scripts and ETL Job

on:
  push:
    branches:
      - main
  workflow_dispatch: # This allows manual triggering of the workflow

jobs:
  update-glue-scripts-and-job:
    runs-on: ubuntu-latest
    environment: trubai_dev

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}


    - name: sync ETL file 
      run: aws s3 sync .github/workflows/etljobs/ s3://data-ingestion-bucket-trubai-dev/glue_cicd_automation/ETL_Jobs/

    - name: Zip files
      run: |
        cd .github/workflows
        zip -r utils.zip utils 
      # Replace '.github/workflows' with the path to your scripts folder

    - name: Sync Zip folder to S3
      run: aws s3 cp .github/workflows/utils.zip s3://data-ingestion-bucket-trubai-dev/glue_cicd_automation/

    - name: Set environment variables from GitHub secrets
      run: |
        echo "GLUE_CONNECTION_LIST=${{ secrets.GLUE_CONNECTION_LIST }}" >> $GITHUB_ENV
        echo "EXTRA_PYTHON_FILES=${{ secrets.EXTRA_PYTHON_FILES }}" >> $GITHUB_ENV
        echo "ROLE_ARN=${{ secrets.ROLE_ARN }}" >> $GITHUB_ENV
        echo "REGION_NAME=${{ secrets.REGION_NAME }}" >> $GITHUB_ENV
        echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> $GITHUB_ENV
      
    - name: install boto3
      run: pip install boto3
      
    - name: Create Glue ETL Job
      run: python .github/workflows/create_glue_job.py # Replace this with the command to execute your Python script for creating the Glue ETL job
