name: Update Glue Scripts and ETL Job

on:
  push:
    branches:
      - main
  workflow_dispatch: # This allows manual triggering of the workflow

jobs:
  update-glue-scripts-and-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Zip files
      run: zip -r utils.zip .github/workflows # Replace '.github/workflows' with the path to your scripts folder

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Sync Zip folder to S3
      run: aws s3 sync utils.zip s3://data-ingestion-bucket-trubai-dev/glue_cicd_automation/ --delete
